module.exports = {
    port: 8000,
    slitherVersion: "0.0.5",
    bodyLimit: "100kb",
    corsHeaders: [],
    detectors: [
        "suicidal",
        "uninitialized-state",
        "uninitialized-storage",
        "arbitrary-send",
        "controlled-delegatecall",
        "reentrancy",
        "locked-ether",
        "constant-function",
        "tx-origin",
        "uninitialized-local",
        "unused-return",
        "assembly",
        "constable-states",
        "external-function",
        "low-level-calls",
        "naming-convention",
        "pragma",
        "solc-version",
        "unused-state"
    ],
    impact: {
        "suicidal": "high",
        "uninitialized-state": "high",
        "uninitialized-storage": "high",
        "arbitrary-send": "high",
        "controlled-delegatecall": "high",
        "reentrancy": "high",
        "locked-ether": "high",
        "constant-function": "high",
        "tx-origin": "medium",
        "uninitialized-local": "medium",
        "unused-return": "medium",
        "assembly": "informational",
        "constable-states": "informational",
        "external-function": "informational",
        "low-level-calls": "informational",
        "naming-convention": "informational",
        "pragma": "informational",
        "solc-version": "informational",
        "unused-state": "informational"
    }
}